### ISSUE TITLE
[origin/0.42.x] ldd error: multiple definition of "rc_logger_[XXX]" .... first definied here

### ISSUE THREAD

**Issue by ShyanJMC** [OpenRC/openrc#415]
When I tried compile it for AARCH64 there are issues with ld for "rc_logger_tty" and "rc_logger_pid":

# Environment variables

export CROSS_COMPILE=aarch64-linux-gnu-
export CC="${CROSS_COMPILE}gcc --sysroot=/usr/aarch64-linux-gnu/ -I/usr/aarch64-linux-gnu/include -I/usr/aarch64-linux-gnu/usr/include/"
export CXX="${CROSS_COMPILE}g++ --sysroot=/usr/aarch64-linux-gnu/ -I/usr/aarch64-linux-gnu/include -I/usr/aarch64-linux-gnu/usr/include/"
export AR="${CROSS_COMPILE}ar"
export AS="${CROSS_COMPILE}as"
export LD="${CROSS_COMPILE}ld --sysroot=/usr/aarch64-linux-gnu/"
export RANLIB="${CROSS_COMPILE}ranlib"
export READELF="${CROSS_COMPILE}readelf"
export STRIP="${CROSS_COMPILE}strip

# Command

DESDIT=/home/clfs/BlackOS/targetfs make PROGLDFLAGS=-static LIBNAME=lib64 MKNET=no MKPREFIX=yes MKSELINUX=no MKSYSVINIT=yes BRANDING=\"BlackOS\" PKG_PREFIX=/home/clfs/BlackOS/targetfs/usr/pkg LOCAL_PREFIX=/home/clfs/BlackOS/targetfs/usr/local PREFIX=/home/clfs/BlackOS/targetfs

# STDERR

- aarch64-linux-gnu-gcc --sysroot=/usr/aarch64-linux-gnu/ -I/usr/aarch64-linux-gnu/include -I/usr/aarch64-linux-gnu/usr/include/  -L../librc -L../libeinfo -O2 -g -std=c99 -Wall -Wextra -Wimplicit -Wshadow -Wformat=2 -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wnested-externs -Winline -Wwrite-strings -Wcast-align -Wcast-qual -Wpointer-arith -Wdeclaration-after-statement -Wsequence-point -Werror=implicit-function-declaration    -Wl,-rpath=/home/clfs/BlackOS/targetfs/lib64 -static  -o openrc rc.o rc-logger.o rc-misc.o rc-plugin.o _usage.o -lutil -lrc -leinfo -Wl,-Bdynamic -ldl 
- /usr/lib/gcc/aarch64-linux-gnu/10.2.0/../../../../aarch64-linux-gnu/bin/ld: rc-logger.o:/home/clfs/linuxfromscratch-sources/openrc/src/rc/rc-logger.h:17: multiple definition of `rc_logger_tty'; rc.o:/home/clfs/linuxfromscratch-sources/openrc/src/rc/rc-logger.h:17: first defined here
- /usr/lib/gcc/aarch64-linux-gnu/10.2.0/../../../../aarch64-linux-gnu/bin/ld: rc-logger.o:/home/clfs/linuxfromscratch-sources/openrc/src/rc/rc-logger.h:16: multiple definition of `rc_logger_pid'; rc.o:/home/clfs/linuxfromscratch-sources/openrc/src/rc/rc-logger.h:16: first defined here

# Update 27-03-2021
This issue is not in branch; remotes/origin/HEAD

**Comment by williamh** [comment]
This should be fixed in 0.43 since it isn't in HEAD according to your update.

I am going to close this, but please re-open if it is still an issue after upgrading to 0.43.

Thanks,

William
